# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 1 */3 *'  # every 3 months
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Zip
        shell: bash
        run: |
          dd if=/dev/urandom of=release.zip bs=1M count=1000

      # Runs a set of commands using the runners shell
      - name: Release
        shell: bash
        run: |
          gh release create `date --iso-8601` release.zip -R $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
