# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 1 */3 *'  # every 3 months
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          repository: 'ArtifexSoftware/mupdf'
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - uses: microsoft/setup-msbuild@v2  

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs a set of commands using the runners shell
      - name: Release
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
